// Generated by info.scce.cinco.product.minidime.generator.sib.iterate.IterateBranchGenerator
	
package sib.iterate

import myPackage.Result
import org.eclipse.xtend.lib.annotations.Data

abstract class Unnamed0IterateBranch extends IterateBranch {
	// Intentionally left blank
}

@Data
class NextUnnamed0IterateBranch extends Unnamed0IterateBranch {
	
	// Variables
	val Result element
	
}

@Data
class ExitUnnamed0IterateBranch extends Unnamed0IterateBranch {
	// Intentionally left blank
}
