// Generated by info.scce.cinco.product.minidime.generator.sib.puttocontext.AbstractPutToContextBranchGenerator
	
package sib.puttocontext

import sib.Branch

abstract class PutToContextBranch extends Branch {
	// Intentionally left blank
}
