// Generated by info.scce.cinco.product.minidime.generator.sib.puttocontext.PutToContextBranchGenerator
	
package sib.puttocontext

import org.eclipse.xtend.lib.annotations.Data

abstract class Unnamed1PutToContextBranch extends PutToContextBranch {
	// Intentionally left blank
}

@Data
class SuccessUnnamed1PutToContextBranch extends Unnamed1PutToContextBranch {
	
	// Variables
	val Boolean reset
	
}
