// Generated by info.scce.cinco.product.minidime.generator.sib.puttocontext.PutToContextSibGenerator
	
package sib.puttocontext

class Unnamed6PutToContextSib extends PutToContextSib {
	
	// Execute method
	def Unnamed6PutToContextBranch execute(String input2) {
		return new SuccessUnnamed6PutToContextBranch(input2)
	}
	
}
