// Generated by info.scce.cinco.product.minidime.generator.sib.puttocontext.PutToContextSibGenerator
	
package sib.puttocontext

class Unnamed5PutToContextSib extends PutToContextSib {
	
	// Execute method
	def Unnamed5PutToContextBranch execute(String input2) {
		return new SuccessUnnamed5PutToContextBranch(input2)
	}
	
}
