// Generated by info.scce.cinco.product.minidime.generator.sib.puttocontext.PutToContextBranchGenerator
	
package sib.puttocontext

import org.eclipse.xtend.lib.annotations.Data

abstract class Unnamed4PutToContextBranch extends PutToContextBranch {
	// Intentionally left blank
}

@Data
class SuccessUnnamed4PutToContextBranch extends Unnamed4PutToContextBranch {
	
	// Variables
	val String input2
	
}
