// Generated by info.scce.cinco.product.minidime.generator.sib.puttocontext.PutToContextSibGenerator
	
package sib.puttocontext

class Unnamed2PutToContextSib extends PutToContextSib {
	
	// Execute method
	def Unnamed2PutToContextBranch execute(Boolean igGFlag) {
		return new SuccessUnnamed2PutToContextBranch(igGFlag)
	}
	
}
