// Generated by info.scce.cinco.product.minidime.generator.sib.puttocontext.PutToContextSibGenerator
	
package sib.puttocontext

class Unnamed4PutToContextSib extends PutToContextSib {
	
	// Execute method
	def Unnamed4PutToContextBranch execute(String input2) {
		return new SuccessUnnamed4PutToContextBranch(input2)
	}
	
}
