// Generated by info.scce.cinco.product.minidime.generator.sib.contains.AbstractContainsBranchGenerator
	
package sib.contains

import sib.Branch

abstract class ContainsBranch extends Branch {
	// Intentionally left blank
}
