// Generated by info.scce.cinco.product.minidime.generator.sib.atomic.AtomicSibGenerator
	
package sib.atomic

import common.DoubleExtension

class CommonRealSibGreaterOrEqualAtomicSib extends AtomicSib {
	
	// Execute method
	def CommonRealSibGreaterOrEqualAtomicBranch execute(Double input1, Double input2) {
		val result = DoubleExtension.greaterOrEqual(input1, input2)
		return new SuccessCommonRealSibGreaterOrEqualAtomicBranch(result)
	}
	
}
