// Generated by info.scce.cinco.product.minidime.generator.sib.atomic.AtomicSibGenerator
	
package sib.atomic

import common.DoubleExtension

class CommonRealSibLessOrEqualAtomicSib extends AtomicSib {
	
	// Execute method
	def CommonRealSibLessOrEqualAtomicBranch execute(Double input1, Double input2) {
		val result = DoubleExtension.lessOrEqual(input1, input2)
		return new SuccessCommonRealSibLessOrEqualAtomicBranch(result)
	}
	
}
