// Generated by info.scce.cinco.product.minidime.generator.sib.atomic.AtomicSibGenerator
	
package sib.atomic

import myPackage.Result
import myPackage.getData

class MyPackagesetResultAtomicSib extends AtomicSib {
	
	// Execute method
	def MyPackagesetResultAtomicBranch execute(Result input0, String input1) {
		getData.setOutcome(input0, input1)
		return new SuccessMyPackagesetResultAtomicBranch
	}
	
}
