// Generated by info.scce.cinco.product.minidime.generator.sib.atomic.AtomicBranchGenerator
	
package sib.atomic

import org.eclipse.xtend.lib.annotations.Data

abstract class MyPackagetextContainsAtomicBranch extends AtomicBranch {
	// Intentionally left blank
}

@Data
class TrueMyPackagetextContainsAtomicBranch extends MyPackagetextContainsAtomicBranch {
	// Intentionally left blank
}

@Data
class FalseMyPackagetextContainsAtomicBranch extends MyPackagetextContainsAtomicBranch {
	// Intentionally left blank
}
