// Generated by info.scce.cinco.product.minidime.generator.sib.atomic.AtomicSibGenerator
	
package sib.atomic

import myPackage.textExt

class MyPackagetextContainsAtomicSib extends AtomicSib {
	
	// Execute method
	def MyPackagetextContainsAtomicBranch execute(String input, String needle) {
		val result = textExt.contains(input, needle)
		if (result) {
			return new TrueMyPackagetextContainsAtomicBranch
		}
		else {
			return new FalseMyPackagetextContainsAtomicBranch
		}
	}
	
}
