// Generated by info.scce.cinco.product.minidime.generator.sib.atomic.AtomicBranchGenerator
	
package sib.atomic

import org.eclipse.xtend.lib.annotations.Data

abstract class MyPackagesetResultAtomicBranch extends AtomicBranch {
	// Intentionally left blank
}

@Data
class SuccessMyPackagesetResultAtomicBranch extends MyPackagesetResultAtomicBranch {
	// Intentionally left blank
}
